# No clear secrets in git. Ciphertext only; the in-cluster sealed-secrets
# controller unseals it into Secret monstermash0-secrets (envFrom). Sealed (strict
# scope) against the dev cluster cert for namespace sdk-apps-dev.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monstermash0-secrets
  namespace: sdk-apps-dev
spec:
  encryptedData:
    INTERACTIVE_SECRET: AgCTl9y9jGyD6PqZ6DD7dwzv+RCXEC9FkK515CcHHWTKvo8bseu0QqxasVkbA4WNNK9t889/8ycvcqLIAtnMB/JV4KKeBSoJhmXZRN74TN+7mtmHfHzQARkaPJn12rnbkBeqc3HzP3pxH9msSoxHBDiUv2CVrUH1B8v9ZCP3EOs1H4uzULeJmWMXVK3oVJsLQuC2XFrsRnlqAJLof2dqh+267+iQZyG5jvWr2Lh583/UBQZdMNCy3ENWIfNOySYJetMYUW25sspIAdBLkt6KmE33iaSzJmblmRl1ELidqYmjXpQdlNW1I0Pn1qAiI6CXRUW8FSPtGwJmSRS3Js/HQQU644QrusG+etwx1DCfGTplEHfLX7xiCShZmSYpFq+5KXKrgjOqRYLAxjf/q9xacCtjjMuyNImdbYEJ+LTlrrjOzp0n5xrVInDXL2WWGG9d2eUekV9yCcoNx3hcX1X8VpJU7kCOFGTd4awpXl4y6O2OgVj5L7JT2xnXMzBmTHKZpu67G/PuN2tPF/MNt3jK6cyF4yANR3cIZPV9rOApcfycXbEG8gYP/9uIckjqd2i7ynctR4l4jWl8Ge2+CwMBOVolr9q5O5Y/yxYT+Ryr+mnmNRCnKjDS4+pqnmzAFlZ5ZyfBVWHi0gK41XHJVs8Em86+p6oVEDcCRlGVdllORzYFNAevWOhiWiNE6qy09MqJsvyFq4ZRNuTRxfa5CmBt4ANglYiHBkbc4W5PKsooeqyvF/Ux1TgLEdGzW1k9fahq/HM=
  template:
    metadata:
      name: monstermash0-secrets
      namespace: sdk-apps-dev
    type: Opaque
